version: '3.8'

services:
  backend:
    build:
      context: .
    environment:
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
      DB_APPLICATION_NAME: ${DB_APPLICATION_NAME}
      SERVICE_BASE_PATH: ${SERVICE_BASE_PATH}
      JWT_TOKEN_EXPIRE_MINUTES: ${JWT_TOKEN_EXPIRE_MINUTES}
      JWT_LONG_TOKEN_EXPIRE_DAYS: ${JWT_LONG_TOKEN_EXPIRE_DAYS}
