version: '3.8'

services:
  backend:
    build:
      context: .
    environment:
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
      DB_APPLICATION_NAME: ${DB_APPLICATION_NAME}
      SERVICE_BASE_PATH: ${SERVICE_BASE_PATH}
      JWT_TOKEN_EXPIRE_MINUTES: ${JWT_TOKEN_EXPIRE_MINUTES}
      JWT_LONG_TOKEN_EXPIRE_DAYS: ${JWT_LONG_TOKEN_EXPIRE_DAYS}
      DEBUG: "false"
      JWT_PRIVATE_KEY: /run/secrets/jwt_private_key
      JWT_PUBLIC_KEY: /run/secrets/jwt_public_key
    secrets:
      - jwt_private_key
      - jwt_public_key

secrets:
  jwt_private_key:
    file: ${JWT_PRIVATE_KEY_LOCATION}
  jwt_public_key:
    file: ${JWT_PUBLIC_KEY_LOCATION}
