"""Added fields to user

Revision ID: d671e067af27
Revises: f5ccf14b6ab6
Create Date: 2023-04-23 16:53:34.831734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd671e067af27'
down_revision = 'f5ccf14b6ab6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user',
        sa.Column('first_name', sa.String(length=40), nullable=True)
    )
    op.add_column(
        'user',
        sa.Column('last_name', sa.String(length=40), nullable=True)
    )
    op.add_column(
        'user',
        sa.Column('date_created', sa.DateTime(),
                  server_default=sa.text('now()'), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date_created')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
