"""Added initial table

Revision ID: f5ccf14b6ab6
Revises:
Create Date: 2023-04-19 21:12:33.457397

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f5ccf14b6ab6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=63), nullable=False),
        sa.Column("passhash", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
